repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Check Rust formatting
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: Run clippy lints (all targets)
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-check-examples
        name: Check examples compilation
        entry: cargo check --examples --all-features
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: Run tests (quick check)
        entry: cargo test --lib --all-features
        language: system
        types: [rust]
        pass_filenames: false